import { SiteConfig } from "@/types"

export const siteConfig: SiteConfig = {
  name: "LunCo",
  description:
  "LunCo is a open-source simulation tool designed for planning space missions, with a focus on lunar settlements. Built with the powerful Godot 4 engine, LunCo aims to revolutionize the way space engineers design and collaborate on complex systems.",
  url: "https://lunco.vercel.app",
  ogImage: "https://lunco.vercel.app/og.png",
  creator: {
    name: "Rod Mamin",
    url: "https://twitter.com/_Difint_",
  },
  keywords: [
    'LunCo',
    'Lunar settlements',
    'Space mission planning',
    'Godot 4 engine',
    'Open-source simulation tool',
    'Lunar base engineering',
    'Unified platform',
    'Requirements management',
    'Models visualizations',
    'Collaborative training',
    'Digital twin',
    'Lunar 3D mapping',
    'Real-time collaboration',
    'Web3 tools',
    'IP-NFT',
    'Intellectual Property Non-Fungible Tokens',
    'Decentralized engineer profiles',
    'Interactive training modules',
    'Linux Mate',
    'Godot installation',
    'FBX2glTF',
    'Git LFS',
    'LunCo repository',
    'Install addons',
    'Community support',
    'Discord server',
    'Twitter',
    'Official website',
    'LinkedIn',
    'YouTube channel',
    'Giveth.io donation',
    'GIV tokens',
    'Profile NFT',
    'Space engineering',
    'Lunar scenarios',
    'Real-world simulations',
    'LunCo development',
    'Lunar colony',
    'Mission design',
    'Spatial data'
  ],
  links: {
    twitter: "https://twitter.com/LunCoSim",
    github: "https://github.com/LunCoSim/lunco-sim",
    linkedin: "https://www.linkedin.com/company/luncosim/",
    discord: "https://discord.gg/GyeTA6Pwqj",
    youtube: "https://www.youtube.com/@LunCoSim",
  },
}
